# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FootballLeagues' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase', '>= 2.5.0'
	pod 'Firebase/AdMob'
	pod 'Firebase/Database'
	pod 'Firebase/Core'

  # Pods for FootballLeagues

  target 'FootballLeaguesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FootballLeaguesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
